Repository DIT112-V21/group-03, pull requests merged in 2021-04, with the labels that each got.

#18 Update smartcar.ino
  arduino/smartcar/smartcar.ino
Labels: sprint#1

#20 Mqtt controller
  .github/workflows/arduino-build.yml
  arduino/smartcar/smartcar.ino
Labels: sprint#1

#34 Controlpanel tests
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/test/controlpanel_test.dart
  smart_pet_buddy/test/widget_test.dart
Labels: test

#37 Flutter app
  .gitignore
  smart_pet_buddy/ios/GoogleService-Info.plist
  smart_pet_buddy/ios/Podfile
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/main.dart
  smart_pet_buddy/lib/mqttclientconnection.dart
Labels: sprint#2

#35 Add flutter CI
  .github/workflows/flutter-build.yml
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/custompage.dart
  smart_pet_buddy/lib/flutter_mqtt_client.dart
  smart_pet_buddy/lib/playpage.dart
  smart_pet_buddy/lib/profilepage.dart
  smart_pet_buddy/lib/signin_page.dart
  smart_pet_buddy/test/controlpanel_test.dart
Labels: sprint#2, test

#38 log out from flutter app
  smart_pet_buddy/lib/homepage.dart
  smart_pet_buddy/lib/register_page.dart
Labels: sprint#2

#40 Controlpanel
  .github/workflows/flutter-build.yml
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/homepage.dart
  smart_pet_buddy/pubspec.lock
  smart_pet_buddy/pubspec.yaml
  smart_pet_buddy/test/controlpanel_test.dart
Labels: sprint#2

#41 Fix steer right bug, add flutter tests and update control panel
  .github/workflows/flutter-build.yml
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/test/controlpanel_test.dart
Labels: refactoring, test

#43 Flutter app
  arduino/smartcar/smartcar.ino
  smart_pet_buddy/lib/bottomnavbar.dart
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/custompage.dart
  smart_pet_buddy/lib/flutter_mqtt_client.dart
  smart_pet_buddy/lib/homepage.dart
  smart_pet_buddy/lib/movementInfo.dart
  smart_pet_buddy/lib/movementWidget.dart
  smart_pet_buddy/lib/profilepage.dart
  smart_pet_buddy/lib/spbMqttClient.dart
Labels: sprint#2

#44 fix control panel connection
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/custompage.dart
  smart_pet_buddy/lib/homepage.dart
Labels: bug, sprint#2
