Repository DIT112-V21/group-03, pull requests merged in 2021-05, with the labels that each got.

#54 Edit profile Feature is ready
  smart_pet_buddy/android/app/build.gradle
  smart_pet_buddy/lib/bottomnavbar.dart
  smart_pet_buddy/lib/edit_profile.dart
  smart_pet_buddy/lib/homepage.dart
  smart_pet_buddy/lib/main.dart
  smart_pet_buddy/lib/password_input.dart
  smart_pet_buddy/lib/profile_widget.dart
  smart_pet_buddy/lib/profilepage.dart
  smart_pet_buddy/lib/register_page.dart
  smart_pet_buddy/lib/signin_page.dart
  smart_pet_buddy/pubspec.lock
  smart_pet_buddy/pubspec.yaml
Labels: sprint#2, user story

#59 Remove go back arrow from appbar when logged in
  smart_pet_buddy/lib/signin_page.dart
  smart_pet_buddy/pubspec.lock
Labels: bug

#60 Stop auto play sessions
  arduino/smartcar/smartcar.ino
  smart_pet_buddy/lib/custompage.dart
  smart_pet_buddy/lib/main.dart
  smart_pet_buddy/lib/movementWidget.dart
Labels: sprint#3

#66 Racemode
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/playpage.dart
  smart_pet_buddy/lib/racemode.dart
  smart_pet_buddy/pubspec.lock
  smart_pet_buddy/pubspec.yaml
Labels: sprint#3

#79 Disable tests
  smart_pet_buddy/test/controlpanel_test.dart
Labels: test

#89 Minor UI changes on racemode and controlpanel
  smart_pet_buddy/lib/controlpage_dialog.dart
  smart_pet_buddy/lib/controlpanel.dart
  smart_pet_buddy/lib/playpage.dart
  smart_pet_buddy/lib/raceMode_dialog.dart
  smart_pet_buddy/lib/racemode.dart
Labels: UI, sprint#4

#90 new UI options for Profile Page and Edit Profile Page
  smart_pet_buddy/lib/appbar_widget.dart
  smart_pet_buddy/lib/bottomnavbar_widget.dart
  smart_pet_buddy/lib/edit_profile.dart
  smart_pet_buddy/lib/profile_page.dart
  smart_pet_buddy/lib/profile_widget.dart
  smart_pet_buddy/lib/profilepage.dart
  smart_pet_buddy/lib/settingspage.dart
  smart_pet_buddy/lib/user.dart
  smart_pet_buddy/lib/user_preferences.dart
  smart_pet_buddy/test/bottomnavbar_widget_Test.dart
Labels: UI

#95 Move sign out button from homepage to profile page
  smart_pet_buddy/lib/homepage.dart
  smart_pet_buddy/lib/profile_page.dart
Labels: UI

#101 Fix renderflex bug
  smart_pet_buddy/lib/main.dart
  smart_pet_buddy/lib/register_page.dart
  smart_pet_buddy/lib/signin_page.dart
Labels: bug
